project:
  type: website

website:
  title: "Car Shopping"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Mercedes EQB 350 4MATIC SUV
        menu:
          - href: specs-mercedes.qmd
            text: Mercedes Specs
          - href: interior-mercedes
            text: Mercedes Interior
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



