project:
  type: website

website:
  title: "Car Shopping"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Mercedes EQB 350 4MATIC SUV
        menu:
          - href: specs-mercedes.qmd
            text: EQB 350 Specs
          - href: interior-mercedes
            text: EQB 350 Interior
      - text: Kia EV9
        menu:
          - href: specs-kia.qmd
            text: EV9 Specs
          - href: interior-kia.qmd
            text: EV9 Interior
      - text: Hyundai IONIQ 9
        menu: 
          - href: specs-hyundai
            text: IONIQ 9 Specs
          - href: interior-hyundai
            text: IONIQ 9 Interior
      - about.qmd

          

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



