project:
  type: website

resources: 
  - images/lucid-air.jpg

website:
  title: "Car Shopping"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Mercedes EQB 350 4MATIC SUV
        menu:
          - href: specs-mercedes.qmd
            text: EQB 350 Price/Specs
          - href: interior-mercedes.qmd
            text: EQB 350 Interior/Features
          - href: overall-mercedes.qmd
            text: Overall
          - href: updates-2026-mercedes.qmd
            text: Speculated Updates for 2026
      - text: Kia EV9
        menu:
          - href: specs-kia.qmd
            text: EV9 Price/Specs
          - href: interior-kia.qmd
            text: EV9 Interior/Features
          - href: overall-kia.qmd
            text: Overall
          - href: updates-2026-kia.qmd
            text: Speculated Updates for 2026
      - text: Hyundai IONIQ 9
        menu: 
          - href: specs-hyundai.qmd
            text: IONIQ 9 Price/Specs
          - href: interior-hyundai.qmd
            text: IONIQ 9 Interior/Features
          - href: overall-hyundai.qmd
            text: Overall
          - href: updates-2026-hyundai.qmd
            text: Speculated Updates for 2026
      - about.qmd

          

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



